### ISSUE TITLE
Compile errors on imported module DebugCanvas.cs

### ISSUE THREAD

**Issue by krso92** [sharkattack51/GarageKit_for_Unity#1]
Hello,
I tried to setup project, I imported required modules and now I have:

> Assets/__ProjectName__/Scripts/Managers/DebugManager.cs(34,16): error CS0122: `DebugConsole.Instance.get' is inaccessible due to its protection level

> Assets/__ProjectName__/Scripts/Managers/DebugManager.cs(34,25):
 error CS1061: Type `DebugConsole' does not contain a definition for `_enable' and no extension method `_enable' of type `DebugConsole' could be found. Are you missing an assembly reference?

> Assets/__ProjectName__/Scripts/Managers/KeyInputManager.cs(68,30): error CS1061: Type `DebugConsole' does not contain a definition for `mode' and no extension method `mode' of type `DebugConsole' could be found. Are you missing an assembly reference?

> Assets/__ProjectName__/Scripts/Managers/KeyInputManager.cs(71,48):
 error CS0117: `DebugConsole' does not contain a definition for `Mode'

I am having 10 errors of this 4 kind.
I thought it was referenced on past revision of file so I tried with first revision and one in between and I am having exact same errors.

Can you help me with this?

**Comment by sharkattack51** [comment]
Hi,
Perhaps the cause is that there is no dependency module DebugConsole.cs.
Please DL from here and try importing.
https://gist.github.com/darktable/1412228

![cap](https://user-images.githubusercontent.com/698447/28550437-c223b990-711b-11e7-874e-b2709c1d8b12.png)

Thanks.

**Comment by krso92** [comment]
Hey,
I am getting these errors with DebugConsole.cs in my project. That same gist reference is in README.
When i was saying:
>  I thought it was referenced on past revision of file so I tried with first revision and one in between and I am having exact same errors.

I was talking about revisions of DebugCanvas.cs on that gist.
I wasn't clear enough, sorry about that.

**Comment by sharkattack51** [comment]
sorry. I confirmed compile error using the latest DebugConsole.cs.
I deleted properties that are not used frequently and fixed them.

https://github.com/sharkattack51/GarageKit_for_Unity/commit/35b6415bb763847a216ced4b2e4bbf8bb9921e6d

thanks for the report.

**Comment by krso92** [comment]
Compile errors gone. Thanks a lot! :)
